### ISSUE TITLE
user module removes user from "All users" group if it isn't expicitly mentioned

### ISSUE THREAD

**Issue by hb9hnt** [menandmice/ansible_micetro#2]
The `user` module removed an existing user from the "All users" group if it is not explicitly specified. Since this is not allowed, the user still remains in the group but the action messes up role membership if roles are to be set.

The problem exists here: 

https://github.com/menandmice/ansible_micetro/blob/main/plugins/modules/user.py#L341

If you don't explicitly set the "All users" group in your yaml, the "All users" group will not be in `wanted_groups` but the user is a member, so Ansible will try to remove this group.

I fixed this problem in my local copy of the module using the following patch - which might not be the nicest solution but it works:

```diff
--- user.py.orig        2023-07-04 14:34:37.804860629 +0200
+++ user.py     2023-07-04 14:35:44.600470118 +0200
@@ -338,7 +338,8 @@
                     # Wanted but not yet present.
                     http_method = "PUT"
                 elif (thisgrp not in wanted_groups) and (
-                    thisgrp in user_data["groups"]
+                    thisgrp in user_data["groups"]) and (
+                    thisgrp["name"] != "All users"
                 ):
                     # Present, but not wanted
                     http_method = "DELETE"
```
Thank you for delivering a proper fix eventually.

--beni

**Comment by tonk** [comment]
I have added your patch to the code and created a new version of the collection (1.0.6) on the Galaxy.

Thank you for reporting this issue.
