### ISSUE TITLE
`doapi()` module helper does not allow API requests with UTF8 encoded non-ascii characters

### ISSUE THREAD

**Issue by hb9hnt** [menandmice/ansible_micetro#3]
Hey all

When trying to create users whose names contain German umlauts, using the `user` Ansible module, I got the following error:

```
 "msg": "Bad Request: A database error has occurred: 22021 ERROR:  invalid byte sequence for encoding \"UTF8\": 0xf6 0x72 0x62 0x65\n. (273)"
```

The problem lies on this line of code: https://github.com/menandmice/ansible_micetro/blob/main/plugins/module_utils/micetro.py#L61

`json.dumps` expects ASCII by default. The following patch fixes the problem:

```diff
--- micetro.py.orig     2023-07-05 08:36:03.142614932 +0200
+++ micetro.py  2023-07-05 08:36:35.103905053 +0200
@@ -58,7 +58,7 @@
                 force_basic_auth=True,
                 url_username=mm_provider["mm_user"],
                 url_password=mm_provider["mm_password"],
-                data=json.dumps(databody),
+                data=json.dumps(databody, ensure_ascii=False).encode("utf8"),
                 validate_certs=False,
                 headers=headers,
             )
```

EDIT: The fix does not fully work because the umlauts end up being scrambled.

EDIT2: The scrambled letters seem to be a separate issue with the JSON API of micetro, unrelated to this issue. It also occurs if you create the user using curl:

```bash
curl -X 'POST' \
  'https://ipam-test.zg.ch/mmws/api/v2/users' \
  -H 'accept: application/json' -v \
  -H 'Authorization: Basic *************' \
  -H 'Content-Type: application/json' \
  -d '{
  "user": {
    "name": "moto",
    "password": "pass!12345",
    "fullName": "Motörhead",
	"authenticationType": "Internal"
   },
  "saveComment": "string"
}'
```

Thanks

--beni

**Comment by tonk** [comment]
I have added your patch to the code and created a new version of the collection (1.0.6) on the Galaxy.

Thank you for reporting this issue.
