### ISSUE TITLE
Wrong zone is selected when Micetro manages both primary and secondary copies of the same zone

### ISSUE THREAD

**Issue by amccann-mbari** [menandmice/ansible_micetro#7]
When discovering the dnsZone ref value if Micetro is managing multiple name servers where one server holds the primary zone and the other servers are secondaries for that zone it is possible for the dnsZone ref value for one of the secondaries to be picked instead of the ref for the primary zone.

Since secondary zones cannot be modified the task fails to apply the DNS record with the message `[WARNING]: Incorrect zone type.` There is also an issue with error handling as the item shows as changed in the Ansible output despite no change being made.

This patch adds a check to make sure only a primary zone ref can be selected.

```diff
--- dnsrecord.py.orig   2024-08-08 14:58:09.863952155 -0700
+++ dnsrecord.py        2024-08-08 14:59:31.644132480 -0700
@@ -277,8 +277,10 @@
     else:
         for zr in zoneresp["dnsZones"]:
             if zr["name"] == rrzone:
-                zoneref = zr["ref"]
-                break
+                if zr["type"] == "Primary":
+                    if "dnsScopeName" not in zr:
+                        zoneref = zr["ref"]
+                        break
```

I also added a check to exclude DNS views for that zone if they exist. I figure that since the module does not provide an option to choose which view to set records in it would be best to only use the default view. If this module is updated to add a parameter for defining a view for the DNS record the `if "dnsScopeName" not in zr:` line can be modified to filter for that view.

**Comment by tonk** [comment]
I will add this fix to the code. 
Unfortunately I cannot test this as I currently don't have a valid Micetro license.

New collection (1.0.10) is uploaded to the Galaxy

**Comment by amccann-mbari** [comment]
Sorry about this but I have identified an issue in the patch I provided.

Turns out in version 2 of the Micetro API, which is what is used by the [Micetro REST API documentation page](https://api.menandmice.com/10.5.0/), it uses `Primary` and `Secondary` for the zone type. This module uses API version 1 which uses `Master` and `Slave` for the zone type.

Here is an update that will check for either `Primary` or `Master` when searching for the primary DNS zone ref.

```diff
--- dnsrecord.py.orig   2024-08-13 16:20:48.401006465 -0700
+++ dnsrecord.py        2024-08-13 16:21:07.001258374 -0700
@@ -277,7 +277,7 @@
     else:
         for zr in zoneresp["dnsZones"]:
             if zr["name"] == rrzone:
-                if zr["type"] == "Primary":
+                if zr["type"] in ["Primary", "Master"]:
                     if "dnsScopeName" not in zr:
                         zoneref = zr["ref"]
                         break
```

**Comment by tonk** [comment]
It was already closed, but I have added the patch and uploaded a new collection
