### ISSUE TITLE
When creating records with multiple subdomains only the leftmost subdomain is used

### ISSUE THREAD

**Issue by amccann-mbari** [menandmice/ansible_micetro#8]
When attempting to create a record with multiple subdomains only the leftmost subdomain is kept. For example when creating a new record under zone `zone.example` `subdomain2.subdomain1.zone.example` gets turned into `subdomain2.zone.example`

The issues is in the code that checks if the name specified in the task is unqualified. The `rrname` variable is changed to the first label of the desired record, the new `rrname` variable is then re-used later for creating the new DNS record which results in just the leftmost label being used when creating a new record.

```diff
--- dnsrecord.py.orig   2024-08-13 16:20:48.401006465 -0700
+++ dnsrecord.py        2024-08-13 16:21:07.001258374 -0700
@@ -300,12 +300,11 @@
     # It could be that the result is empty. This sometimes happens when
     # a record is stored with just the name and not the FQDN. This depends on
     # the recordtype
-    rrname = module.params.get("name")
     if len(iparesp.get("dnsRecords", [])) == 0:
-        rrname = rrname.split(".")[0]
+        rrname_short = rrname.split(".")[0]
         refs = "%s/DNSRecords?filter=name=%s and type=%s and data=%s" % (
             zoneref,
-            rrname,
+            rrname_short,
             rrtype,
             rrdata,
         )
```

This patch also removes the line `rrname = module.params.get("name")` which is redundant and bypasses the check that strips extra spaces off the name string.

I have tested this change against my Micetro instance and it works when specifying both proper dot terminated fully qualified domain names and unqualified domain names.

If there are any additional test you would like me to run just let me know and I can tests against my Micetro instance.

**Comment by tonk** [comment]
I have added this patch and created a new collection. 1.0.11

Thanks for the help.
